### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#10]
1. Шрифты в правой колонке отличаются от макета (https://shimonevt.github.io/FSD-Project-1-Webpack-/colors-and-type.html)
2.  На ховере дродаун начинает отличаться 
![image](https://user-images.githubusercontent.com/21965602/126427230-53c6bc3a-3e3d-42b4-9c6f-f3579d719399.png)

3. Въезд-выезд стрелочка не кликабельна и не вызывает открытия дропдауна (с этим можно разобраться с помощью одного только CSS)  https://shimonevt.github.io/FSD-Project-1-Webpack-/form-elements.html
4. 
![image](https://user-images.githubusercontent.com/21965602/126427372-7d45d976-a935-46c6-90da-1323660e177f.png)
5. Дропдауны в хедере: хотелось бы что бы при клике на внешнюю область дропдауны в мобильном и десктопом навбарах сворачивались + дропдауны сливаются с фоном, если фон белый.
6. Отрицательная сумма (если уж делаешь подсчет, то надо такие вещи предусматривать)
![image](https://user-images.githubusercontent.com/21965602/126427439-75f926a1-d6e0-4565-b429-2c809574735b.png)
7. 
![image](https://user-images.githubusercontent.com/21965602/126427568-ed7a9eff-8b7e-4b15-bc70-c613c6db15db.png)
8. Границы у футера
![image](https://user-images.githubusercontent.com/21965602/126427594-0a474ca2-6e77-4ced-8e87-cedda34fce0c.png)
9. Адаптивность 
![image](https://user-images.githubusercontent.com/21965602/126427762-a9828409-efa2-42fe-90a7-e556aebd0961.png)
![image](https://user-images.githubusercontent.com/21965602/126427778-e6a5331e-6dcf-49ec-be70-17fe25a01619.png)
![image](https://user-images.githubusercontent.com/21965602/126427806-805fedf6-e87e-4c49-ab1f-30a791d76204.png)

**Comment by shimonevt** [comment]
@essserrr , касательно 2 пункта: ховер не должен давать никакого изменения цвета рамки?

**Comment by essserrr** [comment]
> @essserrr , касательно 2 пункта: ховер не должен давать никакого изменения цвета рамки?

Когда открыт дропдаун и на инпут дропдауна наводишь мышку, то нижные углы становились круглыми. Это неправильно.
