### ISSUE TITLE
Общие правки

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#11]
1. Очень интересная запись, для чего она нужна? 
![image](https://user-images.githubusercontent.com/21965602/126427917-227ccf1c-e6bb-4a24-8c9e-c9f860862d26.png)
2. У этого есть более приятная форма записи без присваивания до переменных и увеличения счетчика вручную
![image](https://user-images.githubusercontent.com/21965602/126427970-daff955f-2b11-4aee-a3c2-5a6cf365e85d.png)
3. Прочекать когда используются лет, а когда конст, поменять при надобности
4. Такие конструкции нужно исключать. Вместо этого сдует сделать объект с вариантами и выбирать нужный вариант по переданному пропу
![image](https://user-images.githubusercontent.com/21965602/126428298-b02317c7-b773-4c2d-8825-44719d3aa7e6.png)
5. Если стиль элемента стоит из нескольких переменных, стили следует писать массивом. Можно даже без джойна.
6. Прочекать когда стоит использовать булевые свойства а когда по типу ключ-значение. Поправить места где булевые не к месту (особенно в миксинах)
7. colors.scss - В именах переменных лучше не указывать конкретный цвет, в процессе разработки цвет может поменяться а имя переменной останется.
8. Поставить автопрефиксер

Коммиты желательно делать по подпунктам.

**Comment by shimonevt** [comment]
@essserrr , по поводу 1 пункта: ну тут происходит сжатие "шариков" в bullet-list , и простое задание 

width: 10px;
height: 10px;

**Comment by essserrr** [comment]
2. 
![image](https://user-images.githubusercontent.com/21965602/127096625-a153f97b-e4f3-4d72-839a-acbdee087f10.png)
![image](https://user-images.githubusercontent.com/21965602/127096668-7a54579d-cab7-4b1d-92bb-c93e3261ea81.png)
Если ты просто хочешь пройти по всем элементам массива/объекта то лучше использовать each
Если ты хочешь скипнуть какой-то элемент, применить какой-нибудь нестандартный счетчик - цикл for, например тут 
![image](https://user-images.githubusercontent.com/21965602/127096889-6a28985e-48dc-4038-b0dc-933dda728b4b.png)

**Comment by essserrr** [comment]
4. Вижу ты не совсем понял как лучше писать. Разберем на примере.
У тебя есть 
![image](https://user-images.githubusercontent.com/21965602/127097306-382d0a84-b361-4239-828c-a07a2f6e3ded.png)
Когда я говорил про выбор класса на основе пропса я имел в виду что-то вроде этого
![image](https://user-images.githubusercontent.com/21965602/127098213-5038f300-b724-4050-aac5-9d7f1b39e0ec.png)
или даже
![image](https://user-images.githubusercontent.com/21965602/127098292-cdb1e8f9-d65e-45dd-bb6d-5a1afd55a244.png)
А если у тебя булевый модифкатор то следует делать так
![image](https://user-images.githubusercontent.com/21965602/127098433-60783237-d005-4783-9a1e-b5115256554d.png)

**Comment by essserrr** [comment]
7. Ты частично уловил мысль, а частично нет.
$black - плохо, $dark - хорошо
$orange - плохо, $excellent - хорошо
Не надо указывать КОНКРЕТНЫЙ цвет. Палитру цветов (темная) - это еще куда ни шло. Но в целом, переменная должна отражать назначение,а не конкретное значение в данный момент. Это как var three = 3 звучит. 
Есть еще популярные цвета вроде promaryColor, secondary и т.п.
Можешь например посомтреть material-ui, как у них именование цветов происходит, но это для общего развития.

В целом как ты написал - уже неплохо

**Comment by essserrr** [comment]
6. Булевые модифкаторы следует использовать когда важно наличие или отсуствие модификатора isActive: true;
Модификаторы типа ключ-значение следует использовать, когда у объекта потенциально может быть больше 2 состояний и важно знать не только наличие или отсуствие, но и значение.
Размеры обычно строят рядами вроже: xs, sm, md, lg, xl.
isBtnSmall:true - плохой выбор. Если ты кнопке захочешь сделать lg Размер придется добавить isBtnLarge:false, а внутри комопнента сложно выбирать размер (намного сложное чем выбрать из объекта по значению поля). Так что в данном случае, на перспективу следовало бы использовать btnSize
const size variants = {sm: "xxxxxxxxxxxxx"}

**Comment by essserrr** [comment]
8. Автопрефиксер не работает. Сравни.
У тебя
![image](https://user-images.githubusercontent.com/21965602/127100588-db78c44c-885c-48b8-8f44-19d52c71580f.png)
У меня
![image](https://user-images.githubusercontent.com/21965602/127100771-9d041981-4f94-46f8-a56f-8ca308d1c6d5.png)
