### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#3]
1. Установить преттифай.
2. Установить stylelint.
3. Установить конфиг от airbnb для eslint.
4. Исправить все ошибки которые выявят пункты выше.
5. По всему проекту: прочекать когда применяется "" а когда '' (pug считай что html), исправить.

**Comment by shimonevt** [comment]
@essserrr , ты имеешь ввиду "prettify" как название npm-пакета?

**Comment by essserrr** [comment]
> @essserrr ,
1) Не обязательно, достаточно что бы везде были выставлены одинаковые отсупы, разрывы строки и т.д.
2)     "stylelint"    "stylelint-config-standard"     "stylelint-order":
[stylelintrc.zip](https://github.com/shimonevt/FSD-Project-1-Webpack-/files/6846590/stylelintrc.zip)
