### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#4]
1. Содержимое js файлов хорошо бы выделять в соотвествующие классы, а в том месте, где сейчас ты все пишешь - только вызывать класс с нужными параметрами.
2. Весь поиск по DOM должен осуществляться с помощью классов, которые начинаются исключительно с префикса js-

**Comment by shimonevt** [comment]
@essserrr , касательно 1 пункта: можно пример того, что имеется ввиду?

**Comment by essserrr** [comment]
> @essserrr , касательно 1 пункта: можно пример того, что имеется ввиду (хотя бы на примере какого-нибудь псевдокода)?

handlerFunction = () => {do cool stuff}

$(slector).handler(handlerFunction)

в

class SomeClass {
handlerFunction = () => {do cool stuff}
subscribe() {
  $(slector).handler(this.handlerFunction)
}
}

потом в файле где ты сейчас объявлвяешь функции:

const instance = new SomeClass 
instance.subscribe()

Это не буквальное руковосдство к следованию, но в целом я думаю поймешь задумку.

**Comment by essserrr** [comment]
Почему SearchRoomButtons оказался недостоин что бы переехать в отдельный файл?

**Comment by shimonevt** [comment]
@essserrr , тогда встает вопрос: нужно лишь js-класс выносить или создавать полноценный модуль с pug и scss файлами?

**Comment by essserrr** [comment]
Просто вынести в отдельный класс. Я так понимаю линтер airbnb ты до конца не настроил в проекте, иначе бы линтер тебе подсказал, что есть правило 1 файл - 1 объявление класса.
