### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#5]
1. Обратить внимание на то, как следует записывать Font Family (подсказка: одного шрифта маловато)
2. Media queries пишутся сразу после каждого правила, а не в конце всего докмента.

**Comment by shimonevt** [comment]
@essserrr, касательно 2 пункта: имеется ввиду компоновать правила по типу 
```
.blocks { ... }
@media ( ... ){
       blocks { ... }
 }
```
?

**Comment by essserrr** [comment]
.blocks { 
... 
@media ( ... ){
 }
}

**Comment by shimonevt** [comment]
@essserrr ,вопрос по поводу 1 пункта: в случае с такими шрифтами, как Material Icons, тоже нужно добавлять "запасные" шрифты?

**Comment by essserrr** [comment]
> @essserrr ,вопрос по поводу 1 пункта: в случае с такими шрифтами, как Material Icons, тоже нужно добавлять "запасные" шрифты?

Если ты знаешь запасные шрифты для иконок, которые бы часто были системными, то никто запретить тебе не сможет. Заменять не стандартный шрифт другим нестандартным несет мало смысла.
