### ISSUE TITLE
PUG

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#6]
1.  Пропсы миксинов лучше передавать как объект, а не как список аргументов
2. Зачем тебе нужен <!DOCTYPE html> не в корневых файлах страницы, а в миксинах?

**Comment by shimonevt** [comment]
@essserrr , "Зачем тебе нужен не в корневых файлах страницы, а в миксинах?" 
"Зачем тебе не нужен " - не нужен что/кто?

**Comment by essserrr** [comment]
> "Зачем тебе не нужен " - не нужен что/кто?
doctype

> и еще вопрос: аргументы можно записывать в формате camelCase?
можно конечно

**Comment by shimonevt** [comment]
@essserrr, а какие кавычки (двойные, одинарные) использовать для передачи параметров в pug миксин?

**Comment by essserrr** [comment]
> @essserrr, а какие кавычки (двойные, одинарные) использовать для передачи пропсов в pug-миксин?

Везде двойные как в HTML
