### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#7]
1. БЭМ класс элемента не может быть представлен только лишь модификатором  без "родителя" в виду Б или Э.
2. Конструкции, зависимые от тэгов, это не то, чего ты хочешь в БЭМ, правила вроде: .блок div {...} стоит переписать где это возможно на классы.
3. Такого рода зависимостей тоже лучше избегать где это возможно
![image](https://user-images.githubusercontent.com/21965602/125383466-66aa3480-e3d2-11eb-8733-67b8f8ad6986.png)
4. Таким образом у тебя код написан вообще почти без модифкаторов, а это уже сигнал. Еще следует прочекать такую вещь: класс active не должен существовать. Должен сощуествовать класс блок_active или блок__элемент_active. Необходимо исправить это по всему проекту.

**Comment by shimonevt** [comment]
@essserrr , касательно пункта 3: имеется ввиду избегать вложенности тегов (.card-booking date-dropdown ) или переопределения стилей?

**Comment by essserrr** [comment]
.card-booking .date-dropdown 
.card-booking .select

Блок не должен устаналивать правила другому блоку. Своим элементам он может что-то установить, чужим нет.

**Comment by shimonevt** [comment]
@essserrr, а каким образом тогда задавать отступы у блоков, которые самостоятельные и внедряются внутрь других блоков (задавать заранее им отступы или вкладывать их в контейнеры, у которых уже будут отступы)?

**Comment by essserrr** [comment]
Обычно ты делаешь варианты для блоков типа  block--modifacator-1, block--modifacator-2, но со внешними отсупами так лучше не делать, поэтому

.block-1
  .block-1

должно стать

.block-1
  .block-1__element
    .block-1
