### ISSUE TITLE
Git styling

### ISSUE THREAD

**Issue by essserrr** [shimonevt/FSD-Project-1-Webpack-#8]
Мы обычно не пишем комментарии в коде, названия коммитов и прочее на русском. Для этого по-умолчанию следует использовать английский, если другого не обоговорено заранее.

**Comment by shimonevt** [comment]
@essserrr, так мне нужно переписать все комментарии, коммиты и прочее на английский?

**Comment by essserrr** [comment]
> @essserrr, так мне нужно переписать все комментарии, коммиты и прочее на английский?

Комменты в коде, если есть, стоит переписать. Коммиты просто прими за правило так писать.
